version: '3'

services:
  web:
    # container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    # Set envrionment variables based on the .env file
    env_file:
      - ./web/.env
    volumes:
      - ./web/src:/app/src
      - ./web/public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - tasks

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./api/.env
    volumes:
      - ./api/src:/app/src
    restart: always
    ports:
      - 3001:3001
    networks:
      - tasks

networks:
  tasks:
    driver: bridge
